In [9]:
import numpy as np
myarr=np.array([[0,1,2,3,4,5,6]],np.int64)       #two daimantional array[[]]
myarr

array([[0, 1, 2, 3]], dtype=int64)

In [16]:
myarr[0,3]

3

In [13]:
myarr.shape

(1, 4)

In [17]:
myarr.dtype

dtype('int64')

# array creation : conversion from the other python structure ->list

In [20]:
arraylist = np.array([[0,10,2,3],[4,50,6,7],[80,9,10,11]])
arraylist

array([[ 0, 10,  2,  3],
       [ 4, 50,  6,  7],
       [80,  9, 10, 11]])

In [21]:
arraylist.size

12

In [22]:
arraylist.shape

(3, 4)

In [23]:
arraylist.dtype

dtype('int32')

# intrinsic array creation objects arange ones zeroes etc 

In [27]:
zeros = np.zeros((2,5))     #it create 2x5 daimantinal array

In [28]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
arange = np.arange(15)   # it is create 0 to n-1 array 

In [30]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
linspace = np.linspace(0,5,4)
linspace

array([0.        , 1.66666667, 3.33333333, 5.        ])