In [9]:
import numpy as np
myarr=np.array([[0,1,2,3,4,5,6]],np.int64)       #two daimantional array[[]]
myarr

array([[0, 1, 2, 3]], dtype=int64)

In [16]:
myarr[0,3]

3

In [13]:
myarr.shape

(1, 4)

In [17]:
myarr.dtype

dtype('int64')

# array creation : conversion from the other python structure ->list

In [20]:
arraylist = np.array([[0,10,2,3],[4,50,6,7],[80,9,10,11]])
arraylist

array([[ 0, 10,  2,  3],
       [ 4, 50,  6,  7],
       [80,  9, 10, 11]])

In [21]:
arraylist.size

12

In [22]:
arraylist.shape

(3, 4)

In [23]:
arraylist.dtype

dtype('int32')

# intrinsic array creation objects arange ones zeroes etc 

In [27]:
zeros = np.zeros((2,5))     #it create 2x5 daimantinal array

In [28]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
arange = np.arange(15)   # it is create 0 to n-1 array 

In [30]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
linspace = np.linspace(0,5,4)
linspace

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [33]:
empty = np.empty((4,6))

In [34]:
empty       # it is  create 4x6 daimantional array and asign random values

array([[ 0.00000000e+000,  0.00000000e+000,  6.76356274e-312,
        -2.51216216e-310,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  6.76356302e-312, -2.56648539e-310],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 2.32210854e-322, -2.66155079e-310,  6.76300157e-312,
         6.95309013e-310,  6.95309013e-310,  6.76300149e-312]])

In [35]:
epmtylike = np.empty_like(linspace)

In [37]:
epmtylike

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [40]:
identity = np.identity(20)

In [41]:
identity     # it is create 20x20 identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [42]:
arr = np.arange(20)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
arr.reshape(2,10)    # it is create 2x10 arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
arr = arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
arr.shape    # one daimantional array

(20,)

# axis


In [53]:
ar = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [54]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
ar.sum(axis=0)     # sum of column

array([12, 15, 18, 21])

In [58]:
ar.sum(axis=1)    # sum of row

array([ 6, 22, 38])

In [59]:
ar.T   #trans of the array

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [60]:
ar.flat # is use to itrate of the array

In [62]:
for item in ar.flat:
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11


In [63]:
ar.ndim  #daimantional of array

2

In [64]:
ar.size


12

In [66]:
ar.nbytes

48

In [68]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
ar[2,3] = 45

In [71]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 45]])

In [72]:
ar.argmin()    # it is return min elements index

0

In [73]:
ar.argmax()   # it is return max element index

11

In [74]:
ar.argmax(axis=0)   # it is return index

array([2, 2, 2, 2], dtype=int64)

In [75]:
ar.argmin(axis=0)     # it is return index

array([0, 0, 0, 0], dtype=int64)

In [76]:
ar.argmax(axis=1)       # it is return index

array([3, 3, 3], dtype=int64)

In [77]:
ar.argmin(axis=0)        # it is return index

array([0, 0, 0, 0], dtype=int64)

In [78]:
ar.argsort()         # it is return index

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [81]:
one = np.array([8,50,4,89,2])

In [82]:
one

array([ 8, 50,  4, 89,  2])

In [83]:
one.argmax()

3

In [84]:
one.argmin()

4

In [85]:
one.argsort()

array([4, 2, 0, 1, 3], dtype=int64)

In [86]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 45]])

In [93]:
ar.shape


(3, 4)

In [88]:
arraylist

array([[ 0, 10,  2,  3],
       [ 4, 50,  6,  7],
       [80,  9, 10, 11]])

In [89]:
ar+arraylist         # sum of two array

array([[ 0, 11,  4,  6],
       [ 8, 55, 12, 14],
       [88, 18, 20, 56]])

In [92]:
arraylist.shape

(3, 4)

In [90]:
# but if it list then
[0,1,2]+[2,8,5]

[0, 1, 2, 2, 8, 5]

In [94]:
arr*arraylist

ValueError: operands could not be broadcast together with shapes (20,) (3,4) 

In [95]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [97]:
ar.max()

45

In [98]:
ar.sum()

100

In [99]:
ar.min()

0

In [100]:
np.where(ar>5)

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [101]:
np.count_nonzero(ar)

11

# mamory size difference between normal array and numpy array

In [104]:
import sys

In [105]:
py_arr = [16,52,3,32]      #python array

In [106]:
np_arr = np.array(py_arr)  # numpy array

In [109]:
sys.getsizeof(1)*len(py_arr)    # python array size

112

In [113]:
np_arr.itemsize*np_arr.size      # this is difference size of both array

16

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [ ]:
data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}
