In [9]:
import numpy as np
myarr=np.array([[0,1,2,3,4,5,6]],np.int64)       #two daimantional array[[]]
myarr

array([[0, 1, 2, 3]], dtype=int64)

In [16]:
myarr[0,3]

3

In [13]:
myarr.shape

(1, 4)

In [17]:
myarr.dtype

dtype('int64')

# array creation : conversion from the other python structure ->list

In [20]:
arraylist = np.array([[0,10,2,3],[4,50,6,7],[80,9,10,11]])
arraylist

array([[ 0, 10,  2,  3],
       [ 4, 50,  6,  7],
       [80,  9, 10, 11]])

In [21]:
arraylist.size

12

In [22]:
arraylist.shape

(3, 4)

In [23]:
arraylist.dtype

dtype('int32')

# intrinsic array creation objects arange ones zeroes etc 

In [27]:
zeros = np.zeros((2,5))     #it create 2x5 daimantinal array

In [28]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
arange = np.arange(15)   # it is create 0 to n-1 array 

In [30]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
linspace = np.linspace(0,5,4)
linspace

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [33]:
empty = np.empty((4,6))

In [34]:
empty       # it is  create 4x6 daimantional array and asign random values

array([[ 0.00000000e+000,  0.00000000e+000,  6.76356274e-312,
        -2.51216216e-310,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  6.76356302e-312, -2.56648539e-310],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 2.32210854e-322, -2.66155079e-310,  6.76300157e-312,
         6.95309013e-310,  6.95309013e-310,  6.76300149e-312]])

In [35]:
epmtylike = np.empty_like(linspace)

In [37]:
epmtylike

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [40]:
identity = np.identity(20)

In [41]:
identity     # it is create 20x20 identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [42]:
arr = np.arange(20)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
arr.reshape(2,10)    # it is create 2x10 arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
arr = arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
arr.shape    # one daimantional array

(20,)